import JobListing from "./JobListing/JobListing";

const Jobs = () => {
  
  const jobPostings = [
    {
      logo: "google",
      work: "fulltime",
      job: "Software Engineer",
      location: "San Francisco, CA",
      posted: "2022-02-15",
      salary: "$120,000 - $150,000",
      field: "Technology",
    },
    {
      logo: "amazon",
      work: "parttime",
      job: "Marketing Coordinator",
      location: "New York, NY",
      posted: "2022-03-01",
      salary: "$50,000 - $60,000",
      field: "Marketing",
    },
    {
      logo: "apple",
      work: "fulltime",
      job: "Product Manager",
      location: "Cupertino, CA",
      posted: "2022-02-28",
      salary: "$130,000 - $160,000",
      field: "Product Management",
    },
    {
      logo: "facebook",
      work: "parttime",
      job: "Content Creator",
      location: "Austin, TX",
      posted: "2022-03-10",
      salary: "$40,000 - $50,000",
      field: "Content Creation",
    },
    {
      logo: "microsoft",
      work: "fulltime",
      job: "Data Scientist",
      location: "Redmond, WA",
      posted: "2022-03-07",
      salary: "$110,000 - $140,000",
      field: "Data Science",
    },
    {
      logo: "netflix",
      work: "fulltime",
      job: "UI/UX Designer",
      location: "Los Angeles, CA",
      posted: "2022-03-12",
      salary: "$90,000 - $120,000",
      field: "Design",
    },
    {
      logo: "uber",
      work: "parttime",
      job: "Driver",
      location: "Boston, MA",
      posted: "2022-03-09",
      salary: "$20 - $30 per hour",
      field: "Transportation",
    },
    {
      logo: "airbnb",
      work: "fulltime",
      job: "Senior Backend Engineer",
      location: "Dublin, Ireland",
      posted: "2022-02-25",
      salary: "€70,000 - €90,000",
      field: "Technology",
    },
    {
      logo: "twitter",
      work: "fulltime",
      job: "Software Engineer",
      location: "New York, NY",
      posted: "2022-03-05",
      salary: "$110,000 - $130,000",
      field: "Technology",
    },
    {
      logo: "linkedin",
      work: "parttime",
      job: "Social Media Manager",
      location: "Toronto, Canada",
      posted: "2022-03-11",
      salary: "$30 - $40 per hour",
      field: "Marketing",
    },
    {
      logo: "tesla",
      work: "fulltime",
      job: "Electrical Engineer",
      location: "Fremont, CA",
      posted: "2022-03-01",
      salary: "$100,000 - $130,000",
      field: "Engineering",
    },
    {
      logo: "shopify",
      work: "fulltime",
      job: "Frontend Developer",
      location: "Ottawa, Canada",
      posted: "2022-03-08",
      salary: "$80,000 - $100,000",
      field: "Technology",
    },
    {
      logo: "adobe",
      work: "fulltime",
      job: "Product Designer",
      location: "San Francisco, CA",
      posted: "2022-03-02",
      salary: "$120,000 - $150,000",
      field: "Design",
    },
    {
      logo: "github",
      work: "parttime",
      job: "Technical Writer",
      location: "Remote",
      posted: "2022-03-04",
      salary: "$30 - $40 per hour",
      field: "Writing",
    },
    {
      logo: "salesforce",
      work: "fulltime",
      job: "Customer Success Manager",
      location: "Chicago, IL",
      posted: "2022-03-06",
      salary: "$80,000 - $100,000",
      field: "Customer Service",
    },
    {
      logo: "slack",
      work: "fulltime",
      job: "Software Engineer",
      location: "Vancouver, Canada",
      posted: "2022-02-27",
      salary: "$90,000 - $120,000",
      field: "Technology",
    },
    {
      logo: "pinterest",
      work: "parttime",
      job: "Content Moderator",
      location: "Remote",
      posted: "2022-03-03",
      salary: "$20 - $30 per hour",
      field: "Content Moderation",
    },
    {
      logo: "zoom",
      work: "fulltime",
      job: "Product Manager",
      location: "San Jose, CA",
      posted: "2022-03-01",
      salary: "$120,000 - $150,000",
      field: "Product Management",
    },
    {
      logo: "dropbox",
      work: "fulltime",
      job: "Marketing Manager",
      location: "New York, NY",
      posted: "2022-03-10",
      salary: "$90,000 - $120,000",
      field: "Marketing",
    },
    {
      logo: "hubspot",
      work: "parttime",
      job: "Copywriter",
      location: "Remote",
      posted: "2022-03-08",
      salary: "$30 - $40 per hour",
      field: "Writing",
    },
    {
      logo: "yelp",
      work: "fulltime",
      job: "Account Manager",
      location: "San Francisco, CA",
      posted: "2022-02-28",
      salary: "$80,000 - $100,000",
      field: "Sales",
    },
    {
      logo: "oracle",
      work: "fulltime",
      job: "Cloud Engineer",
      location: "Austin, TX",
      posted: "2022-03-09",
      salary: "$100,000 - $130,000",
      field: "Technology",
    },
    {
      logo: "wordpress",
      work: "parttime",
      job: "Social Media Coordinator",
      location: "Remote",
      posted: "2022-03-05",
      salary: "$20 - $30 per hour",
      field: "Marketing",
    },
    {
      logo: "square",
      work: "fulltime",
      job: "Backend Engineer",
      location: "San Francisco, CA",
      posted: "2022-03-12",
      salary: "$120,000 - $150,000",
      field: "Technology",
    },
    {
      logo: "twitter",
      work: "fulltime",
      job: "Data Analyst",
      location: "New York, NY",
      posted: "2022-03-14",
      salary: "$80,000 - $100,000",
      field: "Data Analysis",
    },
    {
      logo: "lyft",
      work: "parttime",
      job: "Driver",
      location: "San Francisco, CA",
      posted: "2022-03-11",
      salary: "$25 - $30 per hour",
      field: "Transportation",
    },
    {
      logo: "linkedin",
      work: "fulltime",
      job: "Recruiter",
      location: "Chicago, IL",
      posted: "2022-03-13",
      salary: "$90,000 - $120,000",
      field: "Human Resources",
    },
    {
      logo: "ebay",
      work: "fulltime",
      job: "Product Manager",
      location: "San Jose, CA",
      posted: "2022-03-16",
      salary: "$120,000 - $150,000",
      field: "Product Management",
    },
    {
      logo: "snapchat",
      work: "parttime",
      job: "Brand Ambassador",
      location: "Los Angeles, CA",
      posted: "2022-03-15",
      salary: "$20 - $30 per hour",
      field: "Marketing",
    },
    {
      logo: "shopify",
      work: "fulltime",
      job: "Frontend Developer",
      location: "Ottawa, Canada",
      posted: "2022-03-18",
      salary: "$90,000 - $120,000",
      field: "Technology",
    },
    {
      logo: "stripe",
      work: "fulltime",
      job: "Customer Support Specialist",
      location: "San Francisco, CA",
      posted: "2022-03-20",
      salary: "$80,000 - $100,000",
      field: "Customer Service",
    },
    {
      logo: "slack",
      work: "parttime",
      job: "Community Manager",
      location: "Remote",
      posted: "2022-03-17",
      salary: "$30 - $40 per hour",
      field: "Community Management",
    },
    {
      logo: "netflix",
      work: "fulltime",
      job: "UI/UX Designer",
      location: "Los Gatos, CA",
      posted: "2022-03-22",
      salary: "$120,000 - $150,000",
      field: "Design",
    },
    {
      logo: "spotify",
      work: "fulltime",
      job: "Data Engineer",
      location: "New York, NY",
      posted: "2022-03-24",
      salary: "$100,000 - $130,000",
      field: "Data Engineering",
    },
    {
      logo: "uber",
      work: "parttime",
      job: "Delivery Driver",
      location: "Boston, MA",
      posted: "2022-03-21",
      salary: "$25 - $30 per hour",
      field: "Transportation",
    },
    {
      logo: "facebook",
      work: "fulltime",
      job: "Product Marketing Manager",
      location: "Menlo Park, CA",
      posted: "2022-03-23",
      salary: "$140,000 - $180,000",
      field: "Marketing",
    },
    {
      logo: "google",
      work: "fulltime",
      job: "Software Engineer",
      location: "Seattle, WA",
      posted: "2022-03-25",
      salary: "$150,000 - $180,000",
      field: "Technology",
    },
    {
      logo: "amazon",
      work: "fulltime",
      job: "Business Intelligence Analyst",
      location: "Austin, TX",
      posted: "2022-03-28",
      salary: "$100,000 - $120,000",
      field: "Data Analysis",
    },
    {
      logo: "microsoft",
      work: "parttime",
      job: "Content Writer",
      location: "Redmond, WA",
      posted: "2022-03-27",
      salary: "$25 - $35 per hour",
      field: "Content Creation",
    },
    {
      logo: "apple",
      work: "fulltime",
      job: "Project Manager",
      location: "Cupertino, CA",
      posted: "2022-03-30",
      salary: "$120,000 - $150,000",
      field: "Project Management",
    },
    {
      logo: "airbnb",
      work: "parttime",
      job: "Event Coordinator",
      location: "San Francisco, CA",
      posted: "2022-03-29",
      salary: "$30 - $40 per hour",
      field: "Event Planning",
    },
    {
      logo: "dropbox",
      work: "fulltime",
      job: "Technical Program Manager",
      location: "Seattle, WA",
      posted: "2022-04-01",
      salary: "$130,000 - $160,000",
      field: "Technology",
    },
    {
      logo: "paypal",
      work: "fulltime",
      job: "Financial Analyst",
      location: "San Jose, CA",
      posted: "2022-04-03",
      salary: "$100,000 - $120,000",
      field: "Finance",
    },
    {
      logo: "hubspot",
      work: "parttime",
      job: "Social Media Manager",
      location: "Remote",
      posted: "2022-04-02",
      salary: "$25 - $35 per hour",
      field: "Social Media",
    },
    {
      logo: "oracle",
      work: "fulltime",
      job: "Database Administrator",
      location: "Redwood City, CA",
      posted: "2022-04-05",
      salary: "$130,000 - $160,000",
      field: "Database Administration",
    },
    {
      logo: "salesforce",
      work: "fulltime",
      job: "Sales Engineer",
      location: "San Francisco, CA",
      posted: "2022-04-07",
      salary: "$140,000 - $170,000",
      field: "Sales",
    },
    {
      logo: "netflix",
      work: "fulltime",
      job: "Product Manager",
      location: "Los Gatos, CA",
      posted: "2022-04-09",
      salary: "$160,000 - $200,000",
      field: "Product Management",
    },
    {
      logo: "spotify",
      work: "parttime",
      job: "Podcast Producer",
      location: "New York, NY",
      posted: "2022-04-08",
      salary: "$30 - $40 per hour",
      field: "Podcasting",
    },
    {
      logo: "ibm",
      work: "fulltime",
      job: "Data Scientist",
      location: "Armonk, NY",
      posted: "2022-04-11",
      salary: "$120,000 - $150,000",
      field: "Data Science",
    },
    {
      logo: "twitter",
      work: "fulltime",
      job: "Frontend Developer",
      location: "San Francisco, CA",
      posted: "2022-04-13",
      salary: "$130,000 - $160,000",
      field: "Technology",
    },
    {
      logo: "linkedin",
      work: "parttime",
      job: "Copywriter",
      location: "Remote",
      posted: "2022-04-12",
      salary: "$25 - $35 per hour",
      field: "Content Creation",
    },
    {
      logo: "dell",
      work: "fulltime",
      job: "Systems Engineer",
      location: "Austin, TX",
      posted: "2022-04-15",
      salary: "$120,000 - $150,000",
      field: "Technology",
    },
    {
      logo: "dropbox",
      work: "fulltime",
      job: "Product Designer",
      location: "San Francisco, CA",
      posted: "2022-04-17",
      salary: "$130,000 - $160,000",
      field: "Design",
    },
    {
      logo: "microsoft",
      work: "parttime",
      job: "Video Editor",
      location: "Redmond, WA",
      posted: "2022-04-16",
      salary: "$25 - $35 per hour",
      field: "Video Production",
    },
    {
      logo: "salesforce",
      work: "fulltime",
      job: "Product Owner",
      location: "San Francisco, CA",
      posted: "2022-04-19",
      salary: "$140,000 - $170,000",
      field: "Product Management",
    },
    {
      logo: "amazon",
      work: "fulltime",
      job: "Software Development Engineer",
      location: "Seattle, WA",
      posted: "2022-04-21",
      salary: "$150,000 - $180,000",
      field: "Technology",
    },
    {
      logo: "oracle",
      work: "parttime",
      job: "Technical Writer",
      location: "Redwood City, CA",
      posted: "2022-04-20",
      salary: "$25 - $35 per hour",
      field: "Technical Writing",
    },
    {
      logo: "airbnb",
      work: "fulltime",
      job: "Marketing Manager",
      location: "San Francisco, CA",
      posted: "2022-04-25",
      salary: "$130,000 - $160,000",
      field: "Marketing",
    },
    {
      logo: "apple",
      work: "fulltime",
      job: "Software Engineer",
      location: "Cupertino, CA",
      posted: "2022-04-27",
      salary: "$140,000 - $170,000",
      field: "Technology",
    },
    {
      logo: "twitter",
      work: "parttime",
      job: "Social Media Manager",
      location: "Remote",
      posted: "2022-04-26",
      salary: "$25 - $35 per hour",
      field: "Social Media",
    },
    {
      logo: "microsoft",
      work: "fulltime",
      job: "Cloud Solutions Architect",
      location: "Redmond, WA",
      posted: "2022-04-29",
      salary: "$170,000 - $200,000",
      field: "Cloud Computing",
    },
    {
      logo: "google",
      work: "fulltime",
      job: "Data Analyst",
      location: "New York, NY",
      posted: "2022-04-30",
      salary: "$100,000 - $130,000",
      field: "Data Analytics",
    },
    {
      logo: "facebook",
      work: "parttime",
      job: "Content Moderator",
      location: "Austin, TX",
      posted: "2022-05-01",
      salary: "$20 - $30 per hour",
      field: "Content Moderation",
    },
    {
      logo: "salesforce",
      work: "fulltime",
      job: "Software Engineering Manager",
      location: "San Francisco, CA",
      posted: "2022-05-02",
      salary: "$200,000 - $250,000",
      field: "Technology",
    },
    {
      logo: "amazon",
      work: "fulltime",
      job: "Product Marketing Manager",
      location: "Seattle, WA",
      posted: "2022-05-03",
      salary: "$140,000 - $170,000",
      field: "Marketing",
    },
    {
      logo: "linkedin",
      work: "parttime",
      job: "Proofreader",
      location: "Remote",
      posted: "2022-05-04",
      salary: "$25 - $35 per hour",
      field: "Proofreading",
    },
    {
      logo: "ibm",
      work: "fulltime",
      job: "Machine Learning Engineer",
      location: "Armonk, NY",
      posted: "2022-05-05",
      salary: "$150,000 - $180,000",
      field: "Machine Learning",
    },
    {
      logo: "dell",
      work: "fulltime",
      job: "Product Manager",
      location: "Austin, TX",
      posted: "2022-05-06",
      salary: "$140,000 - $170,000",
      field: "Product Management",
    },
    {
      logo: "netflix",
      work: "fulltime",
      job: "Senior Data Scientist",
      location: "Los Angeles, CA",
      posted: "2022-05-08",
      salary: "$180,000 - $220,000",
      field: "Data Science",
    },
    {
      logo: "uber",
      work: "fulltime",
      job: "Product Designer",
      location: "San Francisco, CA",
      posted: "2022-05-09",
      salary: "$120,000 - $150,000",
      field: "Design",
    },
    {
      logo: "tesla",
      work: "fulltime",
      job: "Senior Mechanical Engineer",
      location: "Fremont, CA",
      posted: "2022-05-10",
      salary: "$150,000 - $180,000",
      field: "Mechanical Engineering",
    },
    {
      logo: "github",
      work: "parttime",
      job: "Technical Writer",
      location: "Remote",
      posted: "2022-05-11",
      salary: "$25 - $35 per hour",
      field: "Technical Writing",
    },
    {
      logo: "oracle",
      work: "fulltime",
      job: "Database Administrator",
      location: "Redwood City, CA",
      posted: "2022-05-12",
      salary: "$130,000 - $160,000",
      field: "Database Administration",
    },
    {
      logo: "snap",
      work: "fulltime",
      job: "Content Strategist",
      location: "Santa Monica, CA",
      posted: "2022-05-13",
      salary: "$100,000 - $130,000",
      field: "Content Strategy",
    },
    {
      logo: "intel",
      work: "parttime",
      job: "Copy Editor",
      location: "Remote",
      posted: "2022-05-14",
      salary: "$20 - $30 per hour",
      field: "Copy Editing",
    },
    {
      logo: "nvidia",
      work: "fulltime",
      job: "Senior Software Engineer",
      location: "Santa Clara, CA",
      posted: "2022-05-15",
      salary: "$170,000 - $200,000",
      field: "Technology",
    },
    {
      logo: "cisco",
      work: "fulltime",
      job: "Network Engineer",
      location: "San Jose, CA",
      posted: "2022-05-16",
      salary: "$130,000 - $160,000",
      field: "Network Engineering",
    },
    {
      logo: "hp",
      work: "parttime",
      job: "Graphic Designer",
      location: "Remote",
      posted: "2022-05-17",
      salary: "$25 - $35 per hour",
      field: "Graphic Design",
    },
    {
      logo: "adobe",
      work: "fulltime",
      job: "Product Manager",
      location: "San Francisco, CA",
      posted: "2022-05-18",
      salary: "$140,000 - $170,000",
      field: "Product Management",
    },
    {
      logo: "microsoft",
      work: "fulltime",
      job: "Cloud Solutions Architect",
      location: "Redmond, WA",
      posted: "2022-05-20",
      salary: "$180,000 - $220,000",
      field: "Cloud Computing",
    },
    {
      logo: "spotify",
      work: "fulltime",
      job: "Senior Software Engineer",
      location: "New York, NY",
      posted: "2022-05-21",
      salary: "$170,000 - $200,000",
      field: "Technology",
    },
    {
      logo: "twitter",
      work: "fulltime",
      job: "Senior UX Designer",
      location: "San Francisco, CA",
      posted: "2022-05-22",
      salary: "$140,000 - $170,000",
      field: "Design",
    },
    {
      logo: "ibm",
      work: "parttime",
      job: "Technical Support Specialist",
      location: "Remote",
      posted: "2022-05-23",
      salary: "$30 - $40 per hour",
      field: "Technical Support",
    },
    {
      logo: "salesforce",
      work: "fulltime",
      job: "Product Marketing Manager",
      location: "San Francisco, CA",
      posted: "2022-05-24",
      salary: "$150,000 - $180,000",
      field: "Marketing",
    },
    {
      logo: "paypal",
      work: "fulltime",
      job: "Senior Software Engineer",
      location: "San Jose, CA",
      posted: "2022-05-25",
      salary: "$170,000 - $200,000",
      field: "Technology",
    },
    {
      logo: "linkedin",
      work: "fulltime",
      job: "Senior Product Manager",
      location: "Sunnyvale, CA",
      posted: "2022-05-26",
      salary: "$180,000 - $220,000",
      field: "Product Management",
    },
    {
      logo: "intel",
      work: "fulltime",
      job: "Hardware Design Engineer",
      location: "Santa Clara, CA",
      posted: "2022-05-27",
      salary: "$150,000 - $180,000",
      field: "Hardware Engineering",
    },
    {
      logo: "atlassian",
      work: "fulltime",
      job: "Senior Product Designer",
      location: "San Francisco, CA",
      posted: "2022-05-28",
      salary: "$150,000 - $180,000",
      field: "Design",
    },
    {
      logo: "pinterest",
      work: "fulltime",
      job: "Senior Software Engineer",
      location: "San Francisco, CA",
      posted: "2022-05-29",
      salary: "$170,000 - $200,000",
      field: "Technology",
    },
    {
      logo: "yelp",
      work: "parttime",
      job: "Content Moderator",
      location: "Remote",
      posted: "2022-05-30",
      salary: "$20 - $30 per hour",
      field: "Content Moderation",
    },
    {
      logo: "apple",
      work: "fulltime",
      job: "Senior Frontend Engineer",
      location: "Cupertino, CA",
      posted: "2022-05-31",
      salary: "$170,000 - $200,000",
      field: "Technology",
    },
    {
      logo: "netflix",
      work: "fulltime",
      job: "Senior Product Manager",
      location: "Los Gatos, CA",
      posted: "2022-06-01",
      salary: "$180,000 - $220,000",
      field: "Product Management",
    },
    {
      logo: "oracle",
      work: "fulltime",
      job: "Senior Database Administrator",
      location: "Redwood City, CA",
      posted: "2022-06-02",
      salary: "$150,000 - $180,000",
      field: "Database Administration",
    },
    {
      logo: "adobe",
      work: "fulltime",
      job: "Senior Product Manager",
      location: "San Francisco, CA",
      posted: "2022-06-03",
      salary: "$180,000 - $220,000",
      field: "Product Management",
    },
    {
      logo: "amazon",
      work: "fulltime",
      job: "Senior Data Scientist",
      location: "Seattle, WA",
      posted: "2022-06-04",
      salary: "$200,000 - $250,000",
      field: "Data Science",
    },
    {
      logo: "google",
      work: "fulltime",
      job: "Product Marketing Manager",
      location: "Mountain View, CA",
      posted: "2022-06-05",
      salary: "$180,000 - $220,000",
      field: "Marketing",
    },
    {
      logo: "facebook",
      work: "fulltime",
      job: "Senior Software Engineer",
      location: "Menlo Park, CA",
      posted: "2022-06-06",
      salary: "$200,000 - $250,000",
      field: "Technology",
    },
    {
      logo: "microsoft",
      work: "fulltime",
      job: "Senior Program Manager",
      location: "Redmond, WA",
      posted: "2022-06-07",
      salary: "$180,000 - $220,000",
      field: "Program Management",
    },
    {
      logo: "spotify",
      work: "fulltime",
      job: "Senior UX Designer",
      location: "Stockholm, Sweden",
      posted: "2022-06-08",
      salary: "900,000 - 1,100,000 SEK",
      field: "Design",
    },
    {
      logo: "twitter",
      work: "fulltime",
      job: "Senior Data Scientist",
      location: "San Francisco, CA",
      posted: "2022-06-09",
      salary: "$180,000 - $220,000",
      field: "Data Science",
    },
    {
      logo: "ibm",
      work: "fulltime",
      job: "Senior Cloud Architect",
      location: "Austin, TX",
      posted: "2022-06-10",
      salary: "$170,000 - $200,000",
      field: "Cloud Computing",
    },
    {
      logo: "salesforce",
      work: "fulltime",
      job: "Senior Product Designer",
      location: "San Francisco, CA",
      posted: "2022-06-11",
      salary: "$150,000 - $180,000",
      field: "Design",
    },
    {
      logo: "airbnb",
      work: "partime",
      job: "Social Media Manager",
      location: "San Francisco, CA",
      posted: "2022-06-12",
      salary: "$50 - $75 per hour",
      field: "Marketing",
    },
    {
      logo: "linkedin",
      work: "fulltime",
      job: "Senior Data Engineer",
      location: "Sunnyvale, CA",
      posted: "2022-06-13",
      salary: "$180,000 - $220,000",
      field: "Data Engineering",
    },
    {
      logo: "uber",
      work: "fulltime",
      job: "Senior Software Engineer",
      location: "San Francisco, CA",
      posted: "2022-06-14",
      salary: "$200,000 - $250,000",
      field: "Technology",
    },
    {
      logo: "paypal",
      work: "fulltime",
      job: "Senior Product Manager",
      location: "San Jose, CA",
      posted: "2022-06-15",
      salary: "$180,000 - $220,000",
      field: "Product Management",
    },
    {
      logo: "intel",
      work: "fulltime",
      job: "Senior Hardware Engineer",
      location: "Santa Clara, CA",
      posted: "2022-06-16",
      salary: "$170,000 - $200,000",
      field: "Hardware Engineering",
    },
    {
      logo: "cisco",
      work: "fulltime",
      job: "Senior Network Engineer",
      location: "San Jose, CA",
      posted: "2022-06-17",
      salary: "$150,000 - $180,000",
      field: "Network Engineering",
    },
    {
      logo: "dell",
      work: "fulltime",
      job: "Senior Software Engineer",
      location: "Austin, TX",
      posted: "2022-06-18",
      salary: "$180,000 - $220,000",
      field: "Technology",
    },
    {
      logo: "vmware",
      work: "fulltime",
      job: "Senior Cloud Architect",
      location: "Palo Alto, CA",
      posted: "2022-06-19",
      salary: "$170,000 - $200,000",
      field: "Cloud Computing",
    },
    {
      logo: "hp",
      work: "fulltime",
      job: "Senior Product Manager",
      location: "Houston, TX",
      posted: "2022-06-20",
      salary: "$150,000 - $180,000",
      field: "Product Management",
    },
    {
      logo: "nvidia",
      work: "fulltime",
      job: "Senior Graphics Engineer",
      location: "Santa Clara, CA",
      posted: "2022-06-21",
      salary: "$200,000 - $250,000",
      field: "Graphics Engineering",
    },
  ];
  
  return (
    <>
    
        <JobListing jobPostings={jobPostings}/>
    </>
  ); 
};

export default Jobs;
